import fs from 'node:fs';
const errors = [];
const required = (value, message) => { if (!value) errors.push(message); };
const lock = JSON.parse(fs.readFileSync('Governance/XCC-002-INHERITANCE.json', 'utf8'));
const readme = fs.readFileSync('README.md', 'utf8');
required(lock.protocol_id === 'XCC-002', 'Protocol ID drift');
required(lock.version === '1.0.0', 'Protocol version drift');
required(lock.status === 'INHERITED_ACTIVE', 'Inheritance status drift');
required(lock.canonical_repository === 'decureton-xencreator/xen-operating-system', 'Canonical owner drift');
required(lock.canonical_commit === '24edcef3883090ded6328b026ee63a6db38e6de1', 'Canonical commit receipt drift');
required(lock.consumer_repository === 'decureton-xencreator/xenengine-site', 'Consumer identity drift');
required(lock.behavior.prompt_time_relevance_check === true, 'Prompt relevance gate disabled');
required(lock.behavior.current_session_repository_probe === true, 'Current-session probe disabled');
required(lock.behavior.memory_is_not_runtime_evidence === true, 'Memory/runtime truth boundary disabled');
required(lock.behavior.shared_contract_requires_federation_scan === true, 'Federation scan gate disabled');
required(lock.behavior.fail_closed_when_sync_unavailable === true, 'Fail-closed sync behavior disabled');
required(lock.privacy.raw_chat_ingestion === false, 'Raw chat ingestion is prohibited');
required(lock.privacy.approved_minimized_outcomes_only === true, 'Privacy minimization gate disabled');
required(readme.includes('XCC-002 Repository-First Chat Synchronization'), 'README inheritance declaration missing');
required(readme.includes('24edcef3883090ded6328b026ee63a6db38e6de1'), 'README canonical receipt drift');
console.log(JSON.stringify({ protocol: 'XCC-002', repository: 'decureton-xencreator/xenengine-site', gate: errors.length ? 'FAIL' : 'PASS', errors }, null, 2));
if (errors.length) process.exit(1);
